// Copyright 2021 Im-Beast. All rights reserved. MIT license.
import { drawPixel, drawText } from "../canvas.ts";
import {
  createComponent,
  ExtendedTuiComponent,
  getCurrentStyler,
} from "../tui_component.ts";
import { Dynamic, TuiObject } from "../types.ts";
import { getStaticValue, textWidth } from "../util.ts";
import { CreateBoxOptions } from "./box.ts";

interface FrameExtension {
  /** Label's text displayed on the button */
  label?: Dynamic<string>;
}

export type CreateFrameOptions = CreateBoxOptions & FrameExtension;

/** Not interactive frame component */
export type FrameComponent = ExtendedTuiComponent<"frame", FrameExtension>;

/**
 * Create LabelComponent
 * It is not interactive by default
 * It can be automatically generated by most of the others components by setting `styler.frame` property
 * @param object - parent of the created box, either Tui instance or other component
 * @param options
 */
export function createFrame(
  object: TuiObject,
  options: CreateFrameOptions,
): FrameComponent {
  const frame: FrameComponent = {
    label: options.label,
    ...createComponent(object, {
      name: "frame",
      interactive: false,
      ...options,
      draw() {
        const styler = getCurrentStyler(frame);
        const { row, column, width, height } = getStaticValue(
          frame.rectangle,
        );

        for (let w = 0; w < width; ++w) {
          drawPixel(frame.canvas, {
            column: column + w,
            row: row,
            value: "─",
            styler,
          });

          drawPixel(frame.canvas, {
            column: column + w,
            row: row + height,
            value: "─",
            styler,
          });
        }

        for (let h = 0; h < height; ++h) {
          drawPixel(frame.canvas, {
            column: column,
            row: row + h,
            value: "│",
            styler,
          });

          drawPixel(frame.canvas, {
            column: column + width,
            row: row + h,
            value: "│",
            styler,
          });
        }

        drawPixel(frame.canvas, {
          column,
          row,
          value: "┌",
          styler,
        });

        drawPixel(frame.canvas, {
          column,
          row: row + height,
          value: "└",
          styler,
        });

        drawPixel(frame.canvas, {
          column: column + width,
          row,
          value: "┐",
          styler,
        });

        drawPixel(frame.canvas, {
          column: column + width,
          row: row + height,
          value: "┘",
          styler,
        });

        if (frame.label && width > 4) {
          let label = getStaticValue(frame.label);

          drawPixel(frame.canvas, {
            column: column + 1,
            row,
            value: "┤",
            styler,
          });

          let tw = textWidth(label);
          while (tw > width - 3) {
            label = label.slice(0, -1);
            tw = textWidth(label);
          }

          drawPixel(frame.canvas, {
            column: column + tw + 2,
            row,
            value: "├",
            styler,
          });

          drawText(frame.canvas, {
            column: column + 2,
            row,
            text: label,
            styler,
          });
        }
      },
    }),
  };

  return frame;
}
